# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"

  # Flask
  config.vm.network "forwarded_port", guest: 5000, host: 8080
  # Network settings
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  

    #folder Settings
  config.vm.synced_folder ".", "/var/www/webapp"


  # Provision python development environment
  # config.vm.provision "shell", inline: <<-SHELL
  #   export HOME=/home/vagrant
  #   sudo apt-get update
  #   sudo apt-get install -yq \
  #     git \
  #     python-venv \
  #     sudo apt-get install python3-venv -y
  #     sudo apt install python3-flask -y
  #     sudo apt install python3-pip -y
  #     sudo python3 -m venv venv
  #     python3 -m venv flask
  # #  su vagrant -c 'cd /vagrant &&
  # #                 make venv/setup &&
  # #                 source venv/bin/activate &&
  # #                 make pip/update'
  # SHELL
end